# Generated by Django 4.0.5 on 2022-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaApp', '0002_faq_faqdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('headline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('first_answer', models.BooleanField()),
                ('second_answer', models.BooleanField()),
                ('third_answer', models.BooleanField()),
            ],
        ),
    ]
