# Generated by Django 4.0.5 on 2022-07-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaApp', '0003_quiz_quizdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LinguaApp.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='first_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='second_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='third_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
