# Generated by Django 4.0.5 on 2022-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaApp', '0004_quizdata_quiz_alter_quiz_headline_alter_quiz_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdata',
            name='first_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='second_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='third_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
